name: Test Actions

on:
  pull_request:
    branches:
      - main

jobs:
  echo-test:
    name: test
    runs-on: ubuntu-20.04

    steps:
      - name: echo
        run: echo si

  pull-status:
    name: pull Request Status
    runs-on: ubuntu-20.04

    steps:
      - uses: ankitjain28may/list-files-in-pr@v1.0
        id: list-files
        with:
          githubToken: ${{ github.token }}
          outputFormat: 'space-delimited'
      - run: |
          for file in ${{ steps.list-files.outputs.pullRequestFiles }}; do
            echo "Changed Files - ${file}."
          done


  run-bash:
    name: Run bash
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run bash
        run: npm run test2
